spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: user
    url: jdbc:mysql://localhost:3306/etudiant-db?createDatabaseIfNotExist=true
    database-platform=org:
      hibernate:
        dialect: MySQL8Dialect
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/scolarite-realm
          jwk-set-uri: http://localhost:8080/realms/scolarite-realm/protocol/openid-connect/certs

server:
  port: 8090
springdoc:
  api-docs:
    enabled: true
    path:  '/api-docs'