spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: user
    url: jdbc:mysql://localhost:3306/etudiant-db?createDatabaseIfNotExist=true
    database-platform=org:
      hibernate:
        dialect: MySQL8Dialect
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8090